- name: install nginx and run
  hosts: worker
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
    name: nginx
    state: present
  - name: Run nginx
    ansible.builtin.service:
    name: nginx
    state: started  